// AUTO-GENERATED by RobotMetrics/lab_support_summary_mcp.py — do not edit by hand.
// Refresh: re-pull the two neon_query calls, overwrite the mcp_*.json files,
// then run `python3 lab_support_summary_mcp.py` and redeploy the WebApp.
export const LAB_SUPPORT_DATA = {
  "titleRange": "Jun 1\u20135",
  "subtitle": "6-week rolling window \u00b7 Mon\u2013Fri \u00b7 >90s hardware faults only (arm / gripper / head cam / neck / chest / other robot issue \u2014 wrist-cam & operational faults excluded)",
  "footer": "Source: Ultra Neon DB via MCP user-ultra \u00b7 station_faults (count + TTR) and station_states (running hours).",
  "generatedAt": "2026-06-08",
  "yAxisLabel": "> 90s faults",
  "weeks": [
    "Apr 27\u2013May 1",
    "May 4\u20138",
    "May 11\u201315",
    "May 18\u201322",
    "May 25\u201329",
    "Jun 1\u20135"
  ],
  "maxY": 40,
  "tickStep": 10,
  "series": [
    {
      "lab": "Lab 1",
      "host": "gen2-005",
      "color": "#4682b4",
      "note": null,
      "counts": [
        0,
        1,
        3,
        1,
        2,
        14
      ]
    },
    {
      "lab": "Lab 2",
      "host": "gen2-109",
      "color": "#e67e22",
      "note": null,
      "counts": [
        0,
        0,
        3,
        3,
        6,
        13
      ]
    },
    {
      "lab": "Lab 5",
      "host": "gen2-007",
      "color": "#3498db",
      "note": null,
      "counts": [
        1,
        4,
        1,
        10,
        6,
        7
      ]
    },
    {
      "lab": "Lab 6",
      "host": "gen2-110",
      "color": "#e74c3c",
      "note": null,
      "counts": [
        0,
        0,
        1,
        6,
        5,
        3
      ]
    },
    {
      "lab": "Lab 7",
      "host": "gen2-108",
      "color": "#f39c12",
      "note": null,
      "counts": [
        0,
        0,
        22,
        7,
        2,
        7
      ]
    },
    {
      "lab": "Lab 8",
      "host": "gen2-105",
      "color": "#1abc9c",
      "note": null,
      "counts": [
        3,
        2,
        1,
        13,
        15,
        8
      ]
    },
    {
      "lab": "Lab 9",
      "host": "gen2-104",
      "color": "#d81b60",
      "note": null,
      "counts": [
        17,
        12,
        15,
        17,
        17,
        35
      ]
    },
    {
      "lab": "Lab 11",
      "host": "gen2-103",
      "color": "#5d6d7e",
      "note": null,
      "counts": [
        32,
        15,
        9,
        19,
        7,
        5
      ]
    },
    {
      "lab": "Lab 12",
      "host": "gen2-018",
      "color": "#a4c639",
      "note": null,
      "counts": [
        3,
        19,
        37,
        22,
        19,
        6
      ]
    },
    {
      "lab": "Lab 13",
      "host": "gen2-102",
      "color": "#0d47a1",
      "note": null,
      "counts": [
        7,
        16,
        17,
        26,
        27,
        31
      ]
    }
  ],
  "cards": [
    {
      "lab": "Lab 1",
      "host": "gen2-005",
      "color": "#4682b4",
      "note": null,
      "slowCount": 14,
      "runHours": 51.4,
      "topFault": {
        "label": "Left arm frozen",
        "ttr": "3h 20m",
        "count": 5
      }
    },
    {
      "lab": "Lab 2",
      "host": "gen2-109",
      "color": "#e67e22",
      "note": null,
      "slowCount": 13,
      "runHours": 47.4,
      "topFault": {
        "label": "Right arm frozen",
        "ttr": "5h 45m",
        "count": 29
      }
    },
    {
      "lab": "Lab 5",
      "host": "gen2-007",
      "color": "#3498db",
      "note": null,
      "slowCount": 7,
      "runHours": 40.6,
      "topFault": {
        "label": "Left arm frozen",
        "ttr": "5h 3m",
        "count": 3
      }
    },
    {
      "lab": "Lab 6",
      "host": "gen2-110",
      "color": "#e74c3c",
      "note": null,
      "slowCount": 3,
      "runHours": 60.1,
      "topFault": {
        "label": "Other robot issue",
        "ttr": "15m",
        "count": 3
      }
    },
    {
      "lab": "Lab 7",
      "host": "gen2-108",
      "color": "#f39c12",
      "note": null,
      "slowCount": 7,
      "runHours": 59.6,
      "topFault": {
        "label": "Right arm frozen",
        "ttr": "1h 9m",
        "count": 2
      }
    },
    {
      "lab": "Lab 8",
      "host": "gen2-105",
      "color": "#1abc9c",
      "note": null,
      "slowCount": 8,
      "runHours": 45.7,
      "topFault": {
        "label": "Left arm frozen",
        "ttr": "51m",
        "count": 52
      }
    },
    {
      "lab": "Lab 9",
      "host": "gen2-104",
      "color": "#d81b60",
      "note": null,
      "slowCount": 35,
      "runHours": 54.1,
      "topFault": {
        "label": "Right arm frozen",
        "ttr": "5h 26m",
        "count": 22
      }
    },
    {
      "lab": "Lab 11",
      "host": "gen2-103",
      "color": "#5d6d7e",
      "note": null,
      "slowCount": 5,
      "runHours": 48.4,
      "topFault": {
        "label": "Right arm frozen",
        "ttr": "1h 58m",
        "count": 23
      }
    },
    {
      "lab": "Lab 12",
      "host": "gen2-018",
      "color": "#a4c639",
      "note": null,
      "slowCount": 6,
      "runHours": 27.6,
      "topFault": {
        "label": "Left arm frozen",
        "ttr": "60m",
        "count": 6
      }
    },
    {
      "lab": "Lab 13",
      "host": "gen2-102",
      "color": "#0d47a1",
      "note": null,
      "slowCount": 31,
      "runHours": 58.5,
      "topFault": {
        "label": "Right arm frozen",
        "ttr": "2h 34m",
        "count": 21
      }
    }
  ]
} as const
